---
- name: NasBook
  hosts: all
  roles:
    #
    # Required
    #
    - { role: factum, tags: [always] }  # <- Collect additional facts

    #
    # Base roles
    #
    - role: cli-downloaders
      tags: [cli-downloaders]
      when: cli_downloaders_managed | default(false)

    - role: docker
      tags: [docker]
      when: docker_managed | default(false)

    - role: editors
      tags: [editors]
      when: editors_managed | default(false)

    - role: upgrade
      tags: [upgrade, upgradable, never]

    #
    # Nas roles
    #
    - role: nginx-proxy
      tags: [nginx-proxy, upgradable]
      when: nginx_proxy_managed | default(false)

    - role: nginx-proxy-manager
      tags: [nginx-proxy-manager, upgradable]
      when: nginx_proxy_manager_managed | default(false)
